name: cubtale_challenge
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.6
  injectable: ^2.4.2
  get_it: ^7.7.0
  flutter_screenutil: ^5.9.3
  json_serializable: ^6.7.1
  rxdart: ^0.27.7
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  dio: ^5.4.3+1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
